/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import counter.Counter;
import javax.swing.JOptionPane;

/**
 *
 * @author YorleydeMaría
 */
public class ClientView extends javax.swing.JFrame {

    /**
     * Creates new form ClientView
     */
    public ClientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdpanel_Client = new javax.swing.JTabbedPane();
        Register_Panel = new javax.swing.JPanel();
        lbl_Name = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_PhoneNumber = new javax.swing.JLabel();
        lbl_Direction = new javax.swing.JLabel();
        lbl_Bierthday = new javax.swing.JLabel();
        lbl_Gender = new javax.swing.JLabel();
        lbl_InstructionCompleteData = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_ID = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_phoneNumber = new javax.swing.JTextField();
        txt_Direction = new javax.swing.JTextField();
        txt_Birthday = new javax.swing.JTextField();
        cbox_GenderRegister = new javax.swing.JComboBox();
        btn_addClient = new javax.swing.JButton();
        btn_ReturnBack = new javax.swing.JButton();
        Register_Panel1 = new javax.swing.JPanel();
        lbl_EmailModify = new javax.swing.JLabel();
        lbl_PhoneNumberModify = new javax.swing.JLabel();
        lbl_DirectionModify = new javax.swing.JLabel();
        lbl_InstructionCompleteData1 = new javax.swing.JLabel();
        txt_IDModify = new javax.swing.JTextField();
        txt_EmailModify = new javax.swing.JTextField();
        txt_PhoneNumberModify = new javax.swing.JTextField();
        txt_DirectionModify = new javax.swing.JTextField();
        btn_ModifyClient = new javax.swing.JButton();
        btn_ReturnBackModify = new javax.swing.JButton();
        btn_SearchClientModify = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_typeModify = new javax.swing.JLabel();
        cbox_typeModify = new javax.swing.JComboBox();
        panel_Consult = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_EnvelopeConsult = new javax.swing.JPanel();
        lbl_CodeDelieveryConsult = new javax.swing.JLabel();
        txt_IDConsult = new javax.swing.JTextField();
        btn_SearchClientConsult = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_TypeDeliveryConsult = new javax.swing.JLabel();
        lbl_statusDeliveryConsult = new javax.swing.JLabel();
        lbl_RemittentConsult = new javax.swing.JLabel();
        lbl_DescriptionDeliveryConsult = new javax.swing.JLabel();
        lbl_dateDelivery = new javax.swing.JLabel();
        lbl_CodeDelieveryConsult1 = new javax.swing.JLabel();
        lbl_TypeDeliveryConsult1 = new javax.swing.JLabel();
        lbl_statusDeliveryConsult1 = new javax.swing.JLabel();
        lbl_RemittentConsult1 = new javax.swing.JLabel();
        lbl_dateDelivery1 = new javax.swing.JLabel();
        lbl_CodeDelieveryConsult2 = new javax.swing.JLabel();
        lbl_TypeDeliveryConsult2 = new javax.swing.JLabel();
        lbl_statusDeliveryConsult2 = new javax.swing.JLabel();
        lbl_RemittentConsult2 = new javax.swing.JLabel();
        lbl_DescriptionDeliveryConsult2 = new javax.swing.JLabel();
        lbl_dateDelivery2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel_PackageConsult = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panel_MagazineConsult = new javax.swing.JPanel();
        lbl_TypeDeliveryConsult3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_DescriptionDeliveryConsult1 = new javax.swing.JLabel();
        lbl_TypeConsultConsult = new javax.swing.JLabel();
        cbox_TypeConsult = new javax.swing.JComboBox();
        panel_Delete = new javax.swing.JPanel();
        txt_IDdelete = new javax.swing.JTextField();
        btn_SearchClientDelete = new javax.swing.JButton();
        lbl_NameModify1 = new javax.swing.JLabel();
        lbl_NameResultDelete = new javax.swing.JLabel();
        btn_Delete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_TypeConsultDelete = new javax.swing.JLabel();
        cbox_TypeDelete = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Register_Panel.setBackground(new java.awt.Color(255, 204, 153));

        lbl_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Name.setText("Nombre Completo");

        lbl_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ID.setText("Identificación");

        lbl_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Email.setText("Correo Electrónico");

        lbl_PhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_PhoneNumber.setText("Teléfono");

        lbl_Direction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Direction.setText("Dirección");

        lbl_Bierthday.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Bierthday.setText("Fecha de Nacimiento");

        lbl_Gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Gender.setText("Género");

        lbl_InstructionCompleteData.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_InstructionCompleteData.setText("Complete los datos que se le solicitan a continuación: ");

        cbox_GenderRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbox_GenderRegister.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Femenino", "Masculino", " ", " " }));

        btn_addClient.setBackground(new java.awt.Color(255, 102, 51));
        btn_addClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_addClient.setText("Registrar");
        btn_addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addClientActionPerformed(evt);
            }
        });

        btn_ReturnBack.setBackground(new java.awt.Color(255, 102, 51));
        btn_ReturnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ReturnBack.setText("Cancelar");

        javax.swing.GroupLayout Register_PanelLayout = new javax.swing.GroupLayout(Register_Panel);
        Register_Panel.setLayout(Register_PanelLayout);
        Register_PanelLayout.setHorizontalGroup(
            Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Register_PanelLayout.createSequentialGroup()
                .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Register_PanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_Gender, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Bierthday, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Direction, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_PhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Email, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbox_GenderRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txt_Name)
                            .addComponent(txt_ID)
                            .addComponent(txt_phoneNumber)
                            .addComponent(txt_Direction)
                            .addComponent(txt_Birthday)))
                    .addGroup(Register_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_InstructionCompleteData)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ReturnBack)
                .addGap(55, 55, 55)
                .addComponent(btn_addClient)
                .addGap(25, 25, 25))
        );
        Register_PanelLayout.setVerticalGroup(
            Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_InstructionCompleteData)
                .addGap(33, 33, 33)
                .addComponent(lbl_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lbl_ID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lbl_Email)
                .addGap(2, 2, 2)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_PhoneNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbl_Direction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbl_Bierthday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Gender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbox_GenderRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addClient)
                    .addComponent(btn_ReturnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbdpanel_Client.addTab("Registrar", Register_Panel);

        Register_Panel1.setBackground(new java.awt.Color(255, 204, 153));

        lbl_EmailModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_EmailModify.setText("Correo Electrónico");

        lbl_PhoneNumberModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_PhoneNumberModify.setText("Telefóno");

        lbl_DirectionModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DirectionModify.setText("Dirección");

        lbl_InstructionCompleteData1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_InstructionCompleteData1.setText("Complete los datos que se le solicitan a continuación: ");

        btn_ModifyClient.setBackground(new java.awt.Color(255, 102, 51));
        btn_ModifyClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ModifyClient.setText("Modificar");
        btn_ModifyClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModifyClientActionPerformed(evt);
            }
        });

        btn_ReturnBackModify.setBackground(new java.awt.Color(255, 102, 51));
        btn_ReturnBackModify.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ReturnBackModify.setText("Cancelar");

        btn_SearchClientModify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_SearchClientModify.setText("Buscar");
        btn_SearchClientModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchClientModifyActionPerformed(evt);
            }
        });

        lbl_typeModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_typeModify.setText("Tipo de consulta");

        cbox_typeModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbox_typeModify.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Identificación del cliente", "Número de Casillero" }));

        javax.swing.GroupLayout Register_Panel1Layout = new javax.swing.GroupLayout(Register_Panel1);
        Register_Panel1.setLayout(Register_Panel1Layout);
        Register_Panel1Layout.setHorizontalGroup(
            Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_Panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ReturnBackModify)
                .addGap(55, 55, 55)
                .addComponent(btn_ModifyClient)
                .addGap(25, 25, 25))
            .addGroup(Register_Panel1Layout.createSequentialGroup()
                .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Register_Panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_InstructionCompleteData1))
                    .addGroup(Register_Panel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_DirectionModify)
                                .addComponent(lbl_PhoneNumberModify)
                                .addComponent(lbl_EmailModify)
                                .addComponent(txt_EmailModify, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(txt_PhoneNumberModify)
                                .addComponent(txt_DirectionModify))
                            .addGroup(Register_Panel1Layout.createSequentialGroup()
                                .addComponent(lbl_typeModify)
                                .addGap(18, 18, 18)
                                .addComponent(cbox_typeModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_IDModify))
                        .addGap(30, 30, 30)
                        .addComponent(btn_SearchClientModify)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        Register_Panel1Layout.setVerticalGroup(
            Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_InstructionCompleteData1)
                .addGap(15, 15, 15)
                .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_typeModify)
                    .addComponent(cbox_typeModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_IDModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchClientModify))
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(lbl_EmailModify)
                .addGap(2, 2, 2)
                .addComponent(txt_EmailModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_PhoneNumberModify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_PhoneNumberModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbl_DirectionModify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_DirectionModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ModifyClient)
                    .addComponent(btn_ReturnBackModify))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tbdpanel_Client.addTab("Modificar", Register_Panel1);

        panel_EnvelopeConsult.setPreferredSize(new java.awt.Dimension(537, 1000));

        javax.swing.GroupLayout panel_EnvelopeConsultLayout = new javax.swing.GroupLayout(panel_EnvelopeConsult);
        panel_EnvelopeConsult.setLayout(panel_EnvelopeConsultLayout);
        panel_EnvelopeConsultLayout.setHorizontalGroup(
            panel_EnvelopeConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        panel_EnvelopeConsultLayout.setVerticalGroup(
            panel_EnvelopeConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_EnvelopeConsult);

        lbl_CodeDelieveryConsult.setText("Código");

        btn_SearchClientConsult.setText("Buscar");

        lbl_TypeDeliveryConsult.setText("Tipo");

        lbl_statusDeliveryConsult.setText("Estado");

        lbl_RemittentConsult.setText("Remitente");

        lbl_DescriptionDeliveryConsult.setText("Descripción");

        lbl_dateDelivery.setText("Fecha");

        lbl_CodeDelieveryConsult1.setText("Código");

        lbl_TypeDeliveryConsult1.setText("Tipo");

        lbl_statusDeliveryConsult1.setText("Estado");

        lbl_RemittentConsult1.setText("Remitente");

        lbl_dateDelivery1.setText("Fecha");

        lbl_CodeDelieveryConsult2.setText("Código");

        lbl_TypeDeliveryConsult2.setText("Tipo");

        lbl_statusDeliveryConsult2.setText("Estado");

        lbl_RemittentConsult2.setText("Remitente");

        lbl_DescriptionDeliveryConsult2.setText("Descripción");

        lbl_dateDelivery2.setText("Fecha");

        panel_PackageConsult.setPreferredSize(new java.awt.Dimension(573, 1000));

        javax.swing.GroupLayout panel_PackageConsultLayout = new javax.swing.GroupLayout(panel_PackageConsult);
        panel_PackageConsult.setLayout(panel_PackageConsultLayout);
        panel_PackageConsultLayout.setHorizontalGroup(
            panel_PackageConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        panel_PackageConsultLayout.setVerticalGroup(
            panel_PackageConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panel_PackageConsult);

        panel_MagazineConsult.setPreferredSize(new java.awt.Dimension(573, 1000));

        javax.swing.GroupLayout panel_MagazineConsultLayout = new javax.swing.GroupLayout(panel_MagazineConsult);
        panel_MagazineConsult.setLayout(panel_MagazineConsultLayout);
        panel_MagazineConsultLayout.setHorizontalGroup(
            panel_MagazineConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        panel_MagazineConsultLayout.setVerticalGroup(
            panel_MagazineConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(panel_MagazineConsult);

        lbl_TypeDeliveryConsult3.setText("Tipo Sobre");

        jLabel1.setText("Tipo Contenido");

        jLabel2.setText("Peso");

        jLabel3.setText("Fragil");

        jLabel4.setText("Peso");

        jLabel5.setText("Tecnológico");

        jLabel6.setText("Catálogo");

        jLabel7.setText("Tema");

        jLabel8.setText("Nombre");

        lbl_DescriptionDeliveryConsult1.setText("Descripción");

        lbl_TypeConsultConsult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TypeConsultConsult.setText("Tipo de consulta");

        cbox_TypeConsult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbox_TypeConsult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Identificación del cliente", "Número de Casillero" }));

        javax.swing.GroupLayout panel_ConsultLayout = new javax.swing.GroupLayout(panel_Consult);
        panel_Consult.setLayout(panel_ConsultLayout);
        panel_ConsultLayout.setHorizontalGroup(
            panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(panel_ConsultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(panel_ConsultLayout.createSequentialGroup()
                        .addComponent(lbl_CodeDelieveryConsult1)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_TypeDeliveryConsult1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_statusDeliveryConsult1)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_RemittentConsult1)
                        .addGap(28, 28, 28)
                        .addComponent(lbl_dateDelivery1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_DescriptionDeliveryConsult1)
                        .addGap(51, 51, 51))
                    .addGroup(panel_ConsultLayout.createSequentialGroup()
                        .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ConsultLayout.createSequentialGroup()
                                .addComponent(lbl_CodeDelieveryConsult)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_TypeDeliveryConsult)
                                .addGap(24, 24, 24)
                                .addComponent(lbl_TypeDeliveryConsult3)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_statusDeliveryConsult)
                                .addGap(14, 14, 14)
                                .addComponent(lbl_RemittentConsult)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_dateDelivery)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(58, 58, 58)
                                .addComponent(lbl_DescriptionDeliveryConsult))
                            .addGroup(panel_ConsultLayout.createSequentialGroup()
                                .addComponent(lbl_CodeDelieveryConsult2)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_TypeDeliveryConsult2)
                                .addGap(38, 38, 38)
                                .addComponent(lbl_statusDeliveryConsult2)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_RemittentConsult2)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_dateDelivery2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel8)
                                .addGap(59, 59, 59)
                                .addComponent(lbl_DescriptionDeliveryConsult2))
                            .addGroup(panel_ConsultLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_ConsultLayout.createSequentialGroup()
                                        .addComponent(lbl_TypeConsultConsult)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbox_TypeConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_ConsultLayout.createSequentialGroup()
                                        .addComponent(txt_IDConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(btn_SearchClientConsult)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_ConsultLayout.setVerticalGroup(
            panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ConsultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TypeConsultConsult)
                    .addComponent(cbox_TypeConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_IDConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchClientConsult))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CodeDelieveryConsult)
                    .addComponent(lbl_TypeDeliveryConsult)
                    .addComponent(lbl_statusDeliveryConsult)
                    .addComponent(lbl_RemittentConsult)
                    .addComponent(lbl_DescriptionDeliveryConsult)
                    .addComponent(lbl_dateDelivery)
                    .addComponent(lbl_TypeDeliveryConsult3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CodeDelieveryConsult1)
                    .addComponent(lbl_TypeDeliveryConsult1)
                    .addComponent(lbl_statusDeliveryConsult1)
                    .addComponent(lbl_RemittentConsult1)
                    .addComponent(lbl_dateDelivery1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lbl_DescriptionDeliveryConsult1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CodeDelieveryConsult2)
                    .addComponent(lbl_TypeDeliveryConsult2)
                    .addComponent(lbl_statusDeliveryConsult2)
                    .addComponent(lbl_RemittentConsult2)
                    .addComponent(lbl_DescriptionDeliveryConsult2)
                    .addComponent(lbl_dateDelivery2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbdpanel_Client.addTab("Consultar", panel_Consult);

        btn_SearchClientDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_SearchClientDelete.setText("Buscar");

        lbl_NameModify1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NameModify1.setText("Nombre Completo");

        btn_Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Delete.setText("Eliminar");

        lbl_TypeConsultDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TypeConsultDelete.setText("Tipo de consulta");

        cbox_TypeDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbox_TypeDelete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Identificación del cliente", "Número de Casillero" }));

        javax.swing.GroupLayout panel_DeleteLayout = new javax.swing.GroupLayout(panel_Delete);
        panel_Delete.setLayout(panel_DeleteLayout);
        panel_DeleteLayout.setHorizontalGroup(
            panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_DeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Delete)
                .addGap(24, 24, 24))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_DeleteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_DeleteLayout.createSequentialGroup()
                        .addComponent(lbl_TypeConsultDelete)
                        .addGap(18, 18, 18)
                        .addComponent(cbox_TypeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_NameModify1)
                    .addGroup(panel_DeleteLayout.createSequentialGroup()
                        .addComponent(txt_IDdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btn_SearchClientDelete))
                    .addGroup(panel_DeleteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl_NameResultDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        panel_DeleteLayout.setVerticalGroup(
            panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DeleteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TypeConsultDelete)
                    .addComponent(cbox_TypeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_IDdelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchClientDelete))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_NameModify1)
                .addGap(18, 18, 18)
                .addComponent(lbl_NameResultDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(btn_Delete)
                .addGap(44, 44, 44))
        );

        tbdpanel_Client.addTab("Eliminar", panel_Delete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdpanel_Client)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdpanel_Client)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addClientActionPerformed
        if(!(txt_Name.getText().equals("")|| txt_ID.getText().equals("")||txt_email.getText().equals("")
          ||txt_phoneNumber.getText().equals("")||txt_Direction.getText().equals("")||txt_Birthday.getText().equals(""))){
            String name= txt_Name.getText();
            int ID= Integer.valueOf(txt_ID.getText());
            String email= txt_email.getText();
            int phone=Integer.valueOf(txt_phoneNumber.getText());
            String direction=txt_Direction.getText();
            String Birthday=txt_Birthday.getText();
            String gender= cbox_GenderRegister.getSelectedItem().toString();
            String error=Counter.getInstance().add_client(ID, name, email, phone, direction, gender, Birthday);
            if ((error.equals(""))!=true){
                JOptionPane.showMessageDialog(null,error);
            }else{
                JOptionPane.showMessageDialog(null,"Su número de locker es:"+String.valueOf(Counter.getInstance().getClient(ID).get_locker()));
            }
            txt_Name.setText("");
            txt_ID.setText("");
            txt_email.setText("");
            txt_phoneNumber.setText("");
            txt_Direction.setText("");
            txt_Birthday.setText("");
            cbox_GenderRegister.setSelectedIndex(0);
        }
        
        
    }//GEN-LAST:event_btn_addClientActionPerformed

    private void btn_ModifyClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModifyClientActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btn_ModifyClientActionPerformed

    private void btn_SearchClientModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchClientModifyActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btn_SearchClientModifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Register_Panel;
    private javax.swing.JPanel Register_Panel1;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_ModifyClient;
    private javax.swing.JButton btn_ReturnBack;
    private javax.swing.JButton btn_ReturnBackModify;
    private javax.swing.JButton btn_SearchClientConsult;
    private javax.swing.JButton btn_SearchClientDelete;
    private javax.swing.JButton btn_SearchClientModify;
    private javax.swing.JButton btn_addClient;
    private javax.swing.JComboBox cbox_GenderRegister;
    private javax.swing.JComboBox cbox_TypeConsult;
    private javax.swing.JComboBox cbox_TypeDelete;
    private javax.swing.JComboBox cbox_typeModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_Bierthday;
    private javax.swing.JLabel lbl_CodeDelieveryConsult;
    private javax.swing.JLabel lbl_CodeDelieveryConsult1;
    private javax.swing.JLabel lbl_CodeDelieveryConsult2;
    private javax.swing.JLabel lbl_DescriptionDeliveryConsult;
    private javax.swing.JLabel lbl_DescriptionDeliveryConsult1;
    private javax.swing.JLabel lbl_DescriptionDeliveryConsult2;
    private javax.swing.JLabel lbl_Direction;
    private javax.swing.JLabel lbl_DirectionModify;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_EmailModify;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_InstructionCompleteData;
    private javax.swing.JLabel lbl_InstructionCompleteData1;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_NameModify1;
    private javax.swing.JLabel lbl_NameResultDelete;
    private javax.swing.JLabel lbl_PhoneNumber;
    private javax.swing.JLabel lbl_PhoneNumberModify;
    private javax.swing.JLabel lbl_RemittentConsult;
    private javax.swing.JLabel lbl_RemittentConsult1;
    private javax.swing.JLabel lbl_RemittentConsult2;
    private javax.swing.JLabel lbl_TypeConsultConsult;
    private javax.swing.JLabel lbl_TypeConsultDelete;
    private javax.swing.JLabel lbl_TypeDeliveryConsult;
    private javax.swing.JLabel lbl_TypeDeliveryConsult1;
    private javax.swing.JLabel lbl_TypeDeliveryConsult2;
    private javax.swing.JLabel lbl_TypeDeliveryConsult3;
    private javax.swing.JLabel lbl_dateDelivery;
    private javax.swing.JLabel lbl_dateDelivery1;
    private javax.swing.JLabel lbl_dateDelivery2;
    private javax.swing.JLabel lbl_statusDeliveryConsult;
    private javax.swing.JLabel lbl_statusDeliveryConsult1;
    private javax.swing.JLabel lbl_statusDeliveryConsult2;
    private javax.swing.JLabel lbl_typeModify;
    private javax.swing.JPanel panel_Consult;
    private javax.swing.JPanel panel_Delete;
    private javax.swing.JPanel panel_EnvelopeConsult;
    private javax.swing.JPanel panel_MagazineConsult;
    private javax.swing.JPanel panel_PackageConsult;
    private javax.swing.JTabbedPane tbdpanel_Client;
    private javax.swing.JTextField txt_Birthday;
    private javax.swing.JTextField txt_Direction;
    private javax.swing.JTextField txt_DirectionModify;
    private javax.swing.JTextField txt_EmailModify;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_IDConsult;
    private javax.swing.JTextField txt_IDModify;
    private javax.swing.JTextField txt_IDdelete;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_PhoneNumberModify;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_phoneNumber;
    // End of variables declaration//GEN-END:variables
}
