/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import counter.Client;
import counter.Counter;
import counter.Envelope;
import counter.Package;
import counter.Magazine;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Arrays.asList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author YorleydeMaría
 */
public class ClientView extends javax.swing.JFrame {

    /**
     * Creates new form ClientView
     */
    public ClientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdpanel_Client = new javax.swing.JTabbedPane();
        Register_Panel = new javax.swing.JPanel();
        lbl_Name = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_PhoneNumber = new javax.swing.JLabel();
        lbl_Direction = new javax.swing.JLabel();
        lbl_Bierthday = new javax.swing.JLabel();
        lbl_Gender = new javax.swing.JLabel();
        lbl_InstructionCompleteData = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_ID = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_phoneNumber = new javax.swing.JTextField();
        txt_Direction = new javax.swing.JTextField();
        txt_Birthday = new javax.swing.JTextField();
        cbox_GenderRegister = new javax.swing.JComboBox();
        btn_addClient = new javax.swing.JButton();
        btn_ReturnBack = new javax.swing.JButton();
        Register_Panel1 = new javax.swing.JPanel();
        lbl_EmailModify = new javax.swing.JLabel();
        lbl_PhoneNumberModify = new javax.swing.JLabel();
        lbl_DirectionModify = new javax.swing.JLabel();
        lbl_InstructionCompleteData1 = new javax.swing.JLabel();
        txt_IDModify = new javax.swing.JTextField();
        txt_EmailModify = new javax.swing.JTextField();
        txt_PhoneNumberModify = new javax.swing.JTextField();
        txt_DirectionModify = new javax.swing.JTextField();
        btn_ModifyClient = new javax.swing.JButton();
        btn_ReturnBackModify = new javax.swing.JButton();
        btn_SearchClientModify = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_typeModify = new javax.swing.JLabel();
        cbox_typeModify = new javax.swing.JComboBox();
        panel_Consult = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_EnvelopeConsult = new javax.swing.JPanel();
        lbl_CodeDelieveryConsult = new javax.swing.JLabel();
        txt_IDConsult = new javax.swing.JTextField();
        btn_SearchClientConsult = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_TypeDeliveryConsult = new javax.swing.JLabel();
        lbl_statusDeliveryConsult = new javax.swing.JLabel();
        lbl_RemittentConsult = new javax.swing.JLabel();
        lbl_DescriptionDeliveryConsult = new javax.swing.JLabel();
        lbl_dateDelivery = new javax.swing.JLabel();
        lbl_CodeDelieveryConsult1 = new javax.swing.JLabel();
        lbl_TypeDeliveryConsult1 = new javax.swing.JLabel();
        lbl_statusDeliveryConsult1 = new javax.swing.JLabel();
        lbl_RemittentConsult1 = new javax.swing.JLabel();
        lbl_dateDelivery1 = new javax.swing.JLabel();
        lbl_CodeDelieveryConsult2 = new javax.swing.JLabel();
        lbl_TypeDeliveryConsult2 = new javax.swing.JLabel();
        lbl_statusDeliveryConsult2 = new javax.swing.JLabel();
        lbl_RemittentConsult2 = new javax.swing.JLabel();
        lbl_DescriptionDeliveryConsult2 = new javax.swing.JLabel();
        lbl_dateDelivery2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel_PackageConsult = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panel_MagazineConsult = new javax.swing.JPanel();
        lbl_TypeDeliveryConsult3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_DescriptionDeliveryConsult1 = new javax.swing.JLabel();
        lbl_TypeConsultConsult = new javax.swing.JLabel();
        cbox_TypeConsult = new javax.swing.JComboBox();
        btn_returnBackConsult = new javax.swing.JButton();
        panel_Delete = new javax.swing.JPanel();
        txt_IDdelete = new javax.swing.JTextField();
        btn_SearchClientDelete = new javax.swing.JButton();
        lbl_NameDelete = new javax.swing.JLabel();
        lbl_NameResultDelete = new javax.swing.JLabel();
        btn_Delete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_TypeConsultDelete = new javax.swing.JLabel();
        cbox_TypeDelete = new javax.swing.JComboBox();
        btn_ReturnBackfromDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_Name1 = new javax.swing.JLabel();
        lbl_ID1 = new javax.swing.JLabel();
        lbl_Email1 = new javax.swing.JLabel();
        lbl_PhoneNumber1 = new javax.swing.JLabel();
        lbl_Direction1 = new javax.swing.JLabel();
        lbl_Bierthday1 = new javax.swing.JLabel();
        lbl_Gender1 = new javax.swing.JLabel();
        lbl_nameINFO = new javax.swing.JLabel();
        lbl_ID_INFO = new javax.swing.JLabel();
        lbl_emailINFO = new javax.swing.JLabel();
        lbl_phoneINFO = new javax.swing.JLabel();
        lbl_DirectionINFO = new javax.swing.JLabel();
        lbl_birthdayINFO = new javax.swing.JLabel();
        lbl_genderINFO = new javax.swing.JLabel();
        lbl_TypeConsultConsult1 = new javax.swing.JLabel();
        cbox_TypeINFO = new javax.swing.JComboBox();
        txt_ID_INFO = new javax.swing.JTextField();
        btn_SearchClientINFO = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btn_returnBackfromInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Register_Panel.setBackground(new java.awt.Color(255, 204, 153));

        lbl_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Name.setText("Nombre Completo");

        lbl_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ID.setText("Identificación");

        lbl_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Email.setText("Correo Electrónico");

        lbl_PhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_PhoneNumber.setText("Teléfono");

        lbl_Direction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Direction.setText("Dirección");

        lbl_Bierthday.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Bierthday.setText("Fecha de Nacimiento");

        lbl_Gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Gender.setText("Género");

        lbl_InstructionCompleteData.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_InstructionCompleteData.setText("Complete los datos que se le solicitan a continuación: ");

        cbox_GenderRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbox_GenderRegister.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Femenino", "Masculino", " ", " " }));

        btn_addClient.setBackground(new java.awt.Color(255, 102, 51));
        btn_addClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_addClient.setText("Registrar");
        btn_addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addClientActionPerformed(evt);
            }
        });

        btn_ReturnBack.setBackground(new java.awt.Color(255, 102, 51));
        btn_ReturnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ReturnBack.setText("Regresar");
        btn_ReturnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReturnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Register_PanelLayout = new javax.swing.GroupLayout(Register_Panel);
        Register_Panel.setLayout(Register_PanelLayout);
        Register_PanelLayout.setHorizontalGroup(
            Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Register_PanelLayout.createSequentialGroup()
                .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Register_PanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_Gender, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Bierthday, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Direction, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_PhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Email, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbox_GenderRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txt_Name)
                            .addComponent(txt_ID)
                            .addComponent(txt_phoneNumber)
                            .addComponent(txt_Direction)
                            .addComponent(txt_Birthday)))
                    .addGroup(Register_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_InstructionCompleteData)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ReturnBack)
                .addGap(55, 55, 55)
                .addComponent(btn_addClient)
                .addGap(25, 25, 25))
        );
        Register_PanelLayout.setVerticalGroup(
            Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_InstructionCompleteData)
                .addGap(33, 33, 33)
                .addComponent(lbl_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lbl_ID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lbl_Email)
                .addGap(2, 2, 2)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_PhoneNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbl_Direction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbl_Bierthday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Gender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbox_GenderRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addClient)
                    .addComponent(btn_ReturnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbdpanel_Client.addTab("Registrar", Register_Panel);

        Register_Panel1.setBackground(new java.awt.Color(255, 204, 153));

        lbl_EmailModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_EmailModify.setText("Correo Electrónico");

        lbl_PhoneNumberModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_PhoneNumberModify.setText("Telefóno");

        lbl_DirectionModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DirectionModify.setText("Dirección");

        lbl_InstructionCompleteData1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_InstructionCompleteData1.setText("Complete los datos que se le solicitan a continuación: ");

        btn_ModifyClient.setBackground(new java.awt.Color(255, 102, 51));
        btn_ModifyClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ModifyClient.setText("Modificar");
        btn_ModifyClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModifyClientActionPerformed(evt);
            }
        });

        btn_ReturnBackModify.setBackground(new java.awt.Color(255, 102, 51));
        btn_ReturnBackModify.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ReturnBackModify.setText("Regresar");
        btn_ReturnBackModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReturnBackModifyActionPerformed(evt);
            }
        });

        btn_SearchClientModify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_SearchClientModify.setText("Buscar");
        btn_SearchClientModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchClientModifyActionPerformed(evt);
            }
        });

        lbl_typeModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_typeModify.setText("Tipo de consulta");

        cbox_typeModify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbox_typeModify.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Identificación del cliente", "Número de Casillero" }));

        javax.swing.GroupLayout Register_Panel1Layout = new javax.swing.GroupLayout(Register_Panel1);
        Register_Panel1.setLayout(Register_Panel1Layout);
        Register_Panel1Layout.setHorizontalGroup(
            Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_Panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ReturnBackModify)
                .addGap(55, 55, 55)
                .addComponent(btn_ModifyClient)
                .addGap(25, 25, 25))
            .addGroup(Register_Panel1Layout.createSequentialGroup()
                .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Register_Panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_InstructionCompleteData1))
                    .addGroup(Register_Panel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_DirectionModify)
                            .addComponent(lbl_PhoneNumberModify)
                            .addComponent(lbl_EmailModify)
                            .addComponent(txt_EmailModify)
                            .addComponent(txt_PhoneNumberModify)
                            .addComponent(txt_DirectionModify)
                            .addGroup(Register_Panel1Layout.createSequentialGroup()
                                .addComponent(lbl_typeModify)
                                .addGap(18, 18, 18)
                                .addComponent(cbox_typeModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_IDModify))
                        .addGap(30, 30, 30)
                        .addComponent(btn_SearchClientModify)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        Register_Panel1Layout.setVerticalGroup(
            Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_InstructionCompleteData1)
                .addGap(15, 15, 15)
                .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_typeModify)
                    .addComponent(cbox_typeModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_IDModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchClientModify))
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(lbl_EmailModify)
                .addGap(2, 2, 2)
                .addComponent(txt_EmailModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_PhoneNumberModify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_PhoneNumberModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbl_DirectionModify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_DirectionModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(Register_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ModifyClient)
                    .addComponent(btn_ReturnBackModify))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        tbdpanel_Client.addTab("Modificar", Register_Panel1);

        panel_Consult.setBackground(new java.awt.Color(255, 204, 153));

        panel_EnvelopeConsult.setBackground(new java.awt.Color(255, 255, 204));
        panel_EnvelopeConsult.setPreferredSize(new java.awt.Dimension(537, 1000));

        javax.swing.GroupLayout panel_EnvelopeConsultLayout = new javax.swing.GroupLayout(panel_EnvelopeConsult);
        panel_EnvelopeConsult.setLayout(panel_EnvelopeConsultLayout);
        panel_EnvelopeConsultLayout.setHorizontalGroup(
            panel_EnvelopeConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        panel_EnvelopeConsultLayout.setVerticalGroup(
            panel_EnvelopeConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_EnvelopeConsult);

        lbl_CodeDelieveryConsult.setText("Código");

        btn_SearchClientConsult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_SearchClientConsult.setText("Buscar");
        btn_SearchClientConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchClientConsultActionPerformed(evt);
            }
        });

        lbl_TypeDeliveryConsult.setText("Tipo");

        lbl_statusDeliveryConsult.setText("Estado");

        lbl_RemittentConsult.setText("Remitente");

        lbl_DescriptionDeliveryConsult.setText("Descripción");

        lbl_dateDelivery.setText("Fecha");

        lbl_CodeDelieveryConsult1.setText("Código");

        lbl_TypeDeliveryConsult1.setText("Tipo");

        lbl_statusDeliveryConsult1.setText("Estado");

        lbl_RemittentConsult1.setText("Remitente");

        lbl_dateDelivery1.setText("Fecha");

        lbl_CodeDelieveryConsult2.setText("Código");

        lbl_TypeDeliveryConsult2.setText("Tipo");

        lbl_statusDeliveryConsult2.setText("Estado");

        lbl_RemittentConsult2.setText("Remitente");

        lbl_DescriptionDeliveryConsult2.setText("Descripción");

        lbl_dateDelivery2.setText("Fecha");

        panel_PackageConsult.setBackground(new java.awt.Color(255, 255, 204));
        panel_PackageConsult.setPreferredSize(new java.awt.Dimension(573, 1000));

        javax.swing.GroupLayout panel_PackageConsultLayout = new javax.swing.GroupLayout(panel_PackageConsult);
        panel_PackageConsult.setLayout(panel_PackageConsultLayout);
        panel_PackageConsultLayout.setHorizontalGroup(
            panel_PackageConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        panel_PackageConsultLayout.setVerticalGroup(
            panel_PackageConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panel_PackageConsult);

        panel_MagazineConsult.setBackground(new java.awt.Color(255, 255, 204));
        panel_MagazineConsult.setPreferredSize(new java.awt.Dimension(573, 1000));

        javax.swing.GroupLayout panel_MagazineConsultLayout = new javax.swing.GroupLayout(panel_MagazineConsult);
        panel_MagazineConsult.setLayout(panel_MagazineConsultLayout);
        panel_MagazineConsultLayout.setHorizontalGroup(
            panel_MagazineConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        panel_MagazineConsultLayout.setVerticalGroup(
            panel_MagazineConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(panel_MagazineConsult);

        lbl_TypeDeliveryConsult3.setText("Tipo Sobre");

        jLabel1.setText("Tipo Contenido");

        jLabel2.setText("Peso");

        jLabel3.setText("Fragil");

        jLabel4.setText("Peso");

        jLabel5.setText("Tecnológico");

        jLabel6.setText("Catálogo");

        jLabel7.setText("Tema");

        jLabel8.setText("Nombre");

        lbl_DescriptionDeliveryConsult1.setText("Descripción");

        lbl_TypeConsultConsult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TypeConsultConsult.setText("Tipo de consulta");

        cbox_TypeConsult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbox_TypeConsult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Identificación del cliente", "Número de Casillero" }));

        btn_returnBackConsult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_returnBackConsult.setText("Regresar");
        btn_returnBackConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnBackConsultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ConsultLayout = new javax.swing.GroupLayout(panel_Consult);
        panel_Consult.setLayout(panel_ConsultLayout);
        panel_ConsultLayout.setHorizontalGroup(
            panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ConsultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ConsultLayout.createSequentialGroup()
                        .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_ConsultLayout.createSequentialGroup()
                                    .addComponent(lbl_CodeDelieveryConsult)
                                    .addGap(27, 27, 27)
                                    .addComponent(lbl_TypeDeliveryConsult)
                                    .addGap(33, 33, 33)
                                    .addComponent(lbl_statusDeliveryConsult)
                                    .addGap(28, 28, 28)
                                    .addComponent(lbl_RemittentConsult)
                                    .addGap(30, 30, 30)
                                    .addComponent(lbl_dateDelivery)
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_TypeDeliveryConsult3)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_DescriptionDeliveryConsult))
                                .addGroup(panel_ConsultLayout.createSequentialGroup()
                                    .addComponent(lbl_CodeDelieveryConsult2)
                                    .addGap(27, 27, 27)
                                    .addComponent(lbl_TypeDeliveryConsult2)
                                    .addGap(27, 27, 27)
                                    .addComponent(lbl_statusDeliveryConsult2)
                                    .addGap(29, 29, 29)
                                    .addComponent(lbl_RemittentConsult2)
                                    .addGap(27, 27, 27)
                                    .addComponent(lbl_dateDelivery2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel7)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel8)
                                    .addGap(59, 59, 59)
                                    .addComponent(lbl_DescriptionDeliveryConsult2))
                                .addGroup(panel_ConsultLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_ConsultLayout.createSequentialGroup()
                                            .addComponent(lbl_TypeConsultConsult)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbox_TypeConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panel_ConsultLayout.createSequentialGroup()
                                            .addComponent(txt_IDConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(53, 53, 53)
                                            .addComponent(btn_SearchClientConsult)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_returnBackConsult)))))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addContainerGap())
                    .addGroup(panel_ConsultLayout.createSequentialGroup()
                        .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ConsultLayout.createSequentialGroup()
                                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_ConsultLayout.createSequentialGroup()
                                        .addComponent(lbl_CodeDelieveryConsult1)
                                        .addGap(26, 26, 26)
                                        .addComponent(lbl_TypeDeliveryConsult1))
                                    .addGroup(panel_ConsultLayout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(lbl_statusDeliveryConsult1)
                                        .addGap(25, 25, 25)
                                        .addComponent(lbl_RemittentConsult1)
                                        .addGap(33, 33, 33)
                                        .addComponent(lbl_dateDelivery1)))
                                .addGap(25, 25, 25)
                                .addComponent(jLabel4)
                                .addGap(124, 124, 124))
                            .addGroup(panel_ConsultLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)))
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(lbl_DescriptionDeliveryConsult1)
                        .addGap(61, 61, 61))))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panel_ConsultLayout.setVerticalGroup(
            panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ConsultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TypeConsultConsult)
                    .addComponent(cbox_TypeConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_IDConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchClientConsult)
                    .addComponent(btn_returnBackConsult))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CodeDelieveryConsult)
                    .addComponent(lbl_TypeDeliveryConsult)
                    .addComponent(lbl_statusDeliveryConsult)
                    .addComponent(lbl_RemittentConsult)
                    .addComponent(lbl_DescriptionDeliveryConsult)
                    .addComponent(lbl_dateDelivery)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lbl_TypeDeliveryConsult3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CodeDelieveryConsult1)
                    .addComponent(lbl_TypeDeliveryConsult1)
                    .addComponent(lbl_statusDeliveryConsult1)
                    .addComponent(lbl_RemittentConsult1)
                    .addComponent(lbl_dateDelivery1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lbl_DescriptionDeliveryConsult1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panel_ConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CodeDelieveryConsult2)
                    .addComponent(lbl_TypeDeliveryConsult2)
                    .addComponent(lbl_statusDeliveryConsult2)
                    .addComponent(lbl_RemittentConsult2)
                    .addComponent(lbl_DescriptionDeliveryConsult2)
                    .addComponent(lbl_dateDelivery2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdpanel_Client.addTab("Consultar", panel_Consult);

        panel_Delete.setBackground(new java.awt.Color(255, 204, 153));

        btn_SearchClientDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_SearchClientDelete.setText("Buscar");
        btn_SearchClientDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchClientDeleteActionPerformed(evt);
            }
        });

        lbl_NameDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Delete.setText("Eliminar");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        lbl_TypeConsultDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TypeConsultDelete.setText("Tipo de consulta");

        cbox_TypeDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbox_TypeDelete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Identificación del cliente", "Número de Casillero" }));

        btn_ReturnBackfromDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ReturnBackfromDelete.setText("Regresar");
        btn_ReturnBackfromDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReturnBackfromDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_DeleteLayout = new javax.swing.GroupLayout(panel_Delete);
        panel_Delete.setLayout(panel_DeleteLayout);
        panel_DeleteLayout.setHorizontalGroup(
            panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_DeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ReturnBackfromDelete)
                .addGap(28, 28, 28)
                .addComponent(btn_Delete)
                .addGap(24, 24, 24))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_DeleteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_DeleteLayout.createSequentialGroup()
                        .addComponent(lbl_TypeConsultDelete)
                        .addGap(18, 18, 18)
                        .addComponent(cbox_TypeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_NameDelete)
                    .addGroup(panel_DeleteLayout.createSequentialGroup()
                        .addComponent(txt_IDdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btn_SearchClientDelete))
                    .addGroup(panel_DeleteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl_NameResultDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        panel_DeleteLayout.setVerticalGroup(
            panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DeleteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TypeConsultDelete)
                    .addComponent(cbox_TypeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_IDdelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchClientDelete))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_NameDelete)
                .addGap(18, 18, 18)
                .addComponent(lbl_NameResultDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addGroup(panel_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Delete)
                    .addComponent(btn_ReturnBackfromDelete))
                .addGap(44, 44, 44))
        );

        tbdpanel_Client.addTab("Eliminar", panel_Delete);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        lbl_Name1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Name1.setText("Nombre Completo");

        lbl_ID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ID1.setText("Identificación");

        lbl_Email1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Email1.setText("Correo Electrónico");

        lbl_PhoneNumber1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_PhoneNumber1.setText("Teléfono");

        lbl_Direction1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Direction1.setText("Dirección");

        lbl_Bierthday1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Bierthday1.setText("Fecha de Nacimiento");

        lbl_Gender1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Gender1.setText("Género");

        lbl_nameINFO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_ID_INFO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_emailINFO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_phoneINFO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_DirectionINFO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_birthdayINFO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_genderINFO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_TypeConsultConsult1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TypeConsultConsult1.setText("Tipo de consulta");

        cbox_TypeINFO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbox_TypeINFO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Identificación del cliente", "Número de Casillero" }));

        btn_SearchClientINFO.setText("Buscar");
        btn_SearchClientINFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchClientINFOActionPerformed(evt);
            }
        });

        btn_returnBackfromInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_returnBackfromInfo.setText("Regresar");
        btn_returnBackfromInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnBackfromInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_TypeConsultConsult1)
                                .addGap(18, 18, 18)
                                .addComponent(cbox_TypeINFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_ID_INFO, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btn_SearchClientINFO))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_ID_INFO, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nameINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lbl_birthdayINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lbl_DirectionINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_genderINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Direction1)
                                .addComponent(lbl_PhoneNumber1)
                                .addComponent(lbl_Bierthday1)
                                .addComponent(lbl_Gender1)))
                        .addComponent(lbl_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Name1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_Email1)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_phoneINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_emailINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_returnBackfromInfo)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TypeConsultConsult1)
                    .addComponent(cbox_TypeINFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ID_INFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchClientINFO))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_Name1)
                .addGap(18, 18, 18)
                .addComponent(lbl_nameINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ID_INFO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbl_Email1)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_emailINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addComponent(lbl_PhoneNumber1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_phoneINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_Direction1)
                .addGap(10, 10, 10)
                .addComponent(lbl_DirectionINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_Bierthday1)
                .addGap(18, 18, 18)
                .addComponent(lbl_birthdayINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Gender1)
                    .addComponent(btn_returnBackfromInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_genderINFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        tbdpanel_Client.addTab("Ver información del cliente", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbdpanel_Client)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbdpanel_Client)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addClientActionPerformed
        if(!(txt_Name.getText().equals("")|| txt_ID.getText().equals("")||txt_email.getText().equals("")
          ||txt_phoneNumber.getText().equals("")||txt_Direction.getText().equals("")||txt_Birthday.getText().equals(""))){
            String name= txt_Name.getText();
            int ID= Integer.valueOf(txt_ID.getText());
            String email= txt_email.getText();
            int phone=Integer.valueOf(txt_phoneNumber.getText());
            String direction=txt_Direction.getText();
            String Birthday=txt_Birthday.getText();
            String gender= cbox_GenderRegister.getSelectedItem().toString();
            String error=Counter.getInstance().add_client(ID, name, email, phone, direction, gender, Birthday);
            if ((error.equals(""))!=true){
                JOptionPane.showMessageDialog(null,error);
            }else{
                JOptionPane.showMessageDialog(null,"Su número de locker es:"+String.valueOf(Counter.getInstance().getClient(ID).get_locker().getNumber()));
            }
            txt_Name.setText("");
            txt_ID.setText("");
            txt_email.setText("");
            txt_phoneNumber.setText("");
            txt_Direction.setText("");
            txt_Birthday.setText("");
            cbox_GenderRegister.setSelectedIndex(0);
        }
        else{
            JOptionPane.showMessageDialog(null,"Debe completar todos los datos solicitados");
        }
        
        
    }//GEN-LAST:event_btn_addClientActionPerformed

    private void btn_ModifyClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModifyClientActionPerformed
        // TODO add your handling code here:
        int ID=0;
        if(txt_IDModify.getText().equals("")){ 
            JOptionPane.showMessageDialog(null,"Disculpe debe completar la informacion solicitdada "+"\n"
                    + "de lo contrario no se puede modificar");
        }else{
        if(!(txt_EmailModify.getText().equals("")|| txt_PhoneNumberModify.getText().equals("")
                ||txt_DirectionModify.getText().equals(""))){
            if(cbox_typeModify.getSelectedItem().toString().equals("Identificación del cliente")){
                Client client=Counter.getInstance().getClient(Integer.valueOf(txt_IDModify.getText()));
                ID= client.get_ID();
            }
            if(cbox_typeModify.getSelectedItem().toString().equals("Número de Casillero")){
               Client client=Counter.getInstance().getClientByLocker(Integer.valueOf(txt_IDModify.getText()));
                ID= client.get_ID();
            }
            
                String email=txt_EmailModify.getText();
                int phone= Integer.valueOf(txt_PhoneNumberModify.getText());
                String direction=txt_DirectionModify.getText();
                String error=Counter.getInstance().modify_client(ID, email, phone, direction);
                if ((error.equals(" "))!=true){
                    JOptionPane.showMessageDialog(null,error);
                }else{
                    JOptionPane.showMessageDialog(null,"El cliente ha sido modificado");
                    txt_EmailModify.setText("");
                    txt_PhoneNumberModify.setText("");
                    txt_DirectionModify.setText("");
                    txt_IDModify.setText("");
                    cbox_typeModify.setSelectedIndex(0);
                }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los espacios deben estar"+"\n"
                    + "con la informacion solicitada");
        }
        }
        
    }//GEN-LAST:event_btn_ModifyClientActionPerformed

    private void btn_SearchClientModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchClientModifyActionPerformed
        // TODO add your handling code here:
        if(cbox_typeModify.getSelectedItem().toString().equals(" ")){
             JOptionPane.showMessageDialog(null,"Debe seleccionar un tipo de busqueda");
        }else{
        if(cbox_typeModify.getSelectedItem().toString().equals("Identificación del cliente")){
            if(!(txt_IDModify.getText().equals(""))){
                Client client=Counter.getInstance().getClient(Integer.valueOf(txt_IDModify.getText()));
                if (client!=null){
                txt_EmailModify.setText(client.get_email());
                txt_PhoneNumberModify.setText(String.valueOf(client.get_phone()));
                txt_DirectionModify.setText(client.get_direction());
            }
            else{
                JOptionPane.showMessageDialog(null,"La identificacion ingresada no pertenece a nincuno de nuestros clientes,"
                                                + "inténtelo de nuevo");
            }
        }else{
                JOptionPane.showMessageDialog(null,"Debe ingersar un numero de identificacion");
            }
     }else{
            if(!(txt_IDModify.getText().equals(""))){
                Client client=Counter.getInstance().getClientByLocker(Integer.valueOf(txt_IDModify.getText()));
                if (client!=null){
                    txt_EmailModify.setText(client.get_email());
                    txt_PhoneNumberModify.setText(String.valueOf(client.get_phone()));
                    txt_DirectionModify.setText(client.get_direction());
                }
                else{
                    JOptionPane.showMessageDialog(null,"El número de casillero ingresado no pertenece a ninguno de nuestros clientes, "
                                                    + "inténtelo de nuevo");
                }
            }else{
                    JOptionPane.showMessageDialog(null,"Debe ingersar un numero de casillero");
                }
            
            }   
            
        }
        
    }//GEN-LAST:event_btn_SearchClientModifyActionPerformed

    private void btn_SearchClientConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchClientConsultActionPerformed
        // TODO add your handling code here:
        int ID=0;
        if(cbox_TypeConsult.getSelectedItem().toString().equals(" ")){
                 JOptionPane.showMessageDialog(null,"Debe seleccionar un tipo de busqueda");
        }else{
        if(cbox_TypeConsult.getSelectedItem().toString().equals("Identificación del cliente")){
            if(!(txt_IDConsult.getText().equals(""))){
                Client client=Counter.getInstance().getClient(Integer.valueOf(txt_IDConsult.getText()));
                if (client!=null){
                    ID=Integer.valueOf(txt_IDConsult.getText());
                    ArrayList <Envelope> envelopesDeliveries=Counter.getInstance().getClient(ID).get_locker().DeliverEnvelope();
                    ArrayList <Package> packagesDeliveries=Counter.getInstance().getClient(ID).get_locker().DeliverPackage();
                    ArrayList <Magazine> magazinesDeliveries=Counter.getInstance().getClient(ID).get_locker().DeliverMagazine();
                    takeOutEachElementsEnvelope(envelopesDeliveries);
                    takeOutEachElementsPackage(packagesDeliveries);
                    takeOutEachElementsMagazine(magazinesDeliveries);
            }
            else{
                JOptionPane.showMessageDialog(null,"La identificacion ingresada no pertenece a nincuno de nuestros clientes,"
                                                + "inténtelo de nuevo");
            }
        }else{
                JOptionPane.showMessageDialog(null,"Debe ingersar un numero de identificacion");
            }
     }else{
            if(!(txt_IDConsult.getText().equals(""))){
                Client client=Counter.getInstance().getClientByLocker(Integer.valueOf(txt_IDConsult.getText()));
                if (client!=null){
                    ID=client.get_ID();
                    ArrayList <Envelope> envelopesDeliveries=Counter.getInstance().getClient(ID).get_locker().DeliverEnvelope();
                    ArrayList <Package> packagesDeliveries=Counter.getInstance().getClient(ID).get_locker().DeliverPackage();
                    ArrayList <Magazine> magazinesDeliveries=Counter.getInstance().getClient(ID).get_locker().DeliverMagazine();
                    takeOutEachElementsEnvelope(envelopesDeliveries);
                    takeOutEachElementsPackage(packagesDeliveries);
                    takeOutEachElementsMagazine(magazinesDeliveries);   
                }
                else{
                    JOptionPane.showMessageDialog(null,"El número de casillero ingresado no pertenece a ninguno de nuestros clientes, "
                                                    + "inténtelo de nuevo");
                }
            }else{
                    JOptionPane.showMessageDialog(null,"Debe ingersar un numero de casillero");
                }  
        }   } 
    }//GEN-LAST:event_btn_SearchClientConsultActionPerformed
    private void  takeOutEachElementsEnvelope(ArrayList<Envelope> envelopesDeliveries){
        for (int iDeliver=0; iDeliver<envelopesDeliveries.size();iDeliver++){
            createLineDisplayE(envelopesDeliveries.get(iDeliver),iDeliver);
        }
    }
    private void  takeOutEachElementsPackage(ArrayList<Package> packagesDeliveries){
         for (int iDeliver=0; iDeliver<packagesDeliveries.size();iDeliver++){
            createLineDisplayP(packagesDeliveries.get(iDeliver),iDeliver);
        }   
    }
    private void  takeOutEachElementsMagazine(ArrayList<Magazine> magazinesDeliveries){
          for (int iDeliver=0; iDeliver<magazinesDeliveries.size();iDeliver++){
            createLineDisplayM(magazinesDeliveries.get(iDeliver),iDeliver);
        }    
    }
    private void createLineDisplayE(Envelope envelope,int iDeliver){
        ArrayList<String> listStrings;
        String code=String.valueOf(envelope.get_code());
        String typeDeliver="Sobre";
        String typeEnvelope=envelope.get_typeEnvelope();
        String remittent=envelope.get_remittent();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        String dateIn = dateFormat.format(envelope.get_date().getTime());
        String typeContent=envelope.get_typeContent();
        String weight=String.valueOf(envelope.get_weight());
        String description=envelope.get_description();
        String status="";
        if(envelope.get_status()){
            status="entregado";
        }else{
            status="pendiente";
        }
        ArrayList<String> packageInfo = new ArrayList<>(asList(code,typeDeliver,status,remittent,dateIn,weight,typeContent,typeEnvelope,description));
        createDropLine(packageInfo,iDeliver,panel_EnvelopeConsult);
        
        
    }
    private void createLineDisplayP(Package pPackage,int iDeliver){
        
        String code=String.valueOf(pPackage.get_code());
        String typeDeliver="Paquete";
        String isTecnological=String.valueOf(pPackage.get_technological());
        String remittent=pPackage.get_remittent();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        String dateIn = dateFormat.format(pPackage.get_date().getTime());
        String isFragile=String.valueOf(pPackage.get_frailness());
        String weight=String.valueOf(pPackage.get_weight());
        String description=pPackage.get_description();
        String status;
        if(pPackage.get_status()){
            status="entregado";
        }else{
            status="pendiente";
        }
        ArrayList<String> packageInfo = new ArrayList<>(asList(code,typeDeliver,status,remittent,dateIn,weight,isTecnological,isFragile,description));
        createDropLine(packageInfo,iDeliver,panel_PackageConsult);
    }
    private void createLineDisplayM(Magazine magazine,int iDeliver){
        String code=String.valueOf(magazine.get_code());
        String typeDeliver="Revista";
        String isCatalog=String.valueOf(magazine.get_catalog());
        String remittent=magazine.get_remittent();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        String dateIn = dateFormat.format(magazine.get_date().getTime());
        String topic=magazine.get_topic();
        String name=magazine.get_name();
        String description=magazine.get_description();
        String status;
        if(magazine.get_status()){
            status="entregado";
        }else{
            status="pendiente";
        }
        ArrayList<String> packageInfo = new ArrayList<>(asList(code,typeDeliver,status,remittent,dateIn,isCatalog,topic,name,description));
        createDropLine(packageInfo,iDeliver,panel_MagazineConsult);
    }
    private void  createDropLine(ArrayList<String> packageInfo,int iDelivery,JPanel panel){
        ////Variables para editar el margen en el que se colocan
            int firstMargenX = 15;
            int firstMargenY = 15;
            int widthLbl = 70;
            int heightLbl = 25;
            int spaceBetweenLblY = 10;
                
                JLabel lbl_code = new JLabel();
                JLabel lbl_deliveryType = new JLabel();
                JLabel lbl_isCommited = new JLabel();
                JLabel lbl_Remittent = new JLabel();
                JLabel lbl_DateIn = new JLabel();
                JLabel lbl_Specific1= new JLabel();
                JLabel lbl_Specific2= new JLabel();
                JLabel lbl_Specific3= new JLabel();
                JLabel lbl_Description = new JLabel();

                lbl_code.setBounds(firstMargenX+widthLbl*0,firstMargenY+(spaceBetweenLblY+heightLbl)*iDelivery,widthLbl,heightLbl);
                lbl_deliveryType.setBounds(firstMargenX+widthLbl*1,firstMargenY+(spaceBetweenLblY+heightLbl)*iDelivery,widthLbl,heightLbl);
                lbl_isCommited.setBounds(firstMargenX+widthLbl*2,firstMargenY+(spaceBetweenLblY+heightLbl)*iDelivery,widthLbl,heightLbl);
                lbl_Remittent.setBounds(firstMargenX+widthLbl*3,firstMargenY+(spaceBetweenLblY+heightLbl)*iDelivery,widthLbl,heightLbl);
                lbl_DateIn.setBounds(firstMargenX+widthLbl*4,firstMargenY+(spaceBetweenLblY+heightLbl)*iDelivery,widthLbl,heightLbl);
                lbl_Specific1.setBounds(firstMargenX+widthLbl*5,firstMargenY+(spaceBetweenLblY+heightLbl)*iDelivery,widthLbl,heightLbl);
                lbl_Specific2.setBounds(firstMargenX+widthLbl*6,firstMargenY+(spaceBetweenLblY+heightLbl)*iDelivery,widthLbl,heightLbl);
                lbl_Specific3.setBounds(firstMargenX+widthLbl*7,firstMargenY+(spaceBetweenLblY+heightLbl)*iDelivery,widthLbl,heightLbl);
                lbl_Description.setBounds(firstMargenX+widthLbl*8,firstMargenY+(spaceBetweenLblY+heightLbl)*iDelivery,widthLbl,heightLbl);
                
                panel.add(lbl_code);
                panel.add(lbl_deliveryType);
                panel.add(lbl_isCommited);
                panel.add(lbl_Remittent);
                panel.add(lbl_DateIn);
                panel.add(lbl_Specific1);
                panel.add(lbl_Specific2);
                panel.add(lbl_Specific3);
                panel.add(lbl_Description);
                
                lbl_code.setText(packageInfo.get(0));
                lbl_deliveryType.setText(packageInfo.get(1));
                lbl_isCommited.setText(packageInfo.get(2));
                lbl_Remittent.setText(packageInfo.get(3));
                lbl_DateIn.setText(packageInfo.get(4));
                lbl_Specific1.setText(packageInfo.get(5));
                lbl_Specific2.setText(packageInfo.get(6));
                lbl_Specific3.setText(packageInfo.get(7));
                lbl_Description.setText(packageInfo.get(8));
               
                
                
            
            panel.updateUI();
    }
    
    private void btn_SearchClientDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchClientDeleteActionPerformed
        // TODO add your handling code here:
        int ID=0;
        if(cbox_TypeDelete.getSelectedItem().toString().equals(" ")){
             JOptionPane.showMessageDialog(null,"Debe seleccionar un tipo de busqueda");
        }else{
            if(cbox_TypeDelete.getSelectedItem().toString().equals("Identificación del cliente")){
                if(!(txt_IDdelete.getText().equals(""))){
                    Client client=Counter.getInstance().getClient(Integer.valueOf(txt_IDdelete.getText()));
                    if (client!=null){
                        lbl_NameDelete.setText("El cliente a eliminar es: ");
                        lbl_NameResultDelete.setText(client.get_name());
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"La identificacion ingresada no pertenece a nincuno de nuestros clientes,"
                                                        + "inténtelo de nuevo");
                        cbox_TypeDelete.setSelectedIndex(0);
                        txt_IDdelete.setText("");
                    }
                }else{
                        JOptionPane.showMessageDialog(null,"Debe ingersar un numero de identificacion");
                        cbox_TypeDelete.setSelectedIndex(0);
                        txt_IDdelete.setText("");
                    }
            }else{
                   if(!(txt_IDdelete.getText().equals(""))){
                       Client client=Counter.getInstance().getClientByLocker(Integer.valueOf(txt_IDdelete.getText()));
                       if (client!=null){
                           lbl_NameDelete.setText("El cliente a eliminar es: ");
                           lbl_NameResultDelete.setText(client.get_name());   
                       }
                       else{
                           JOptionPane.showMessageDialog(null,"El número de casillero ingresado no pertenece a ninguno de nuestros clientes, "
                                                           + "inténtelo de nuevo");
                           cbox_TypeDelete.setSelectedIndex(0);
                           txt_IDdelete.setText("");
                       }
                   }else{
                           JOptionPane.showMessageDialog(null,"Debe ingersar un numero de casillero");
                           cbox_TypeDelete.setSelectedIndex(0);
                           txt_IDdelete.setText("");
                        }  
            } }
        
    }//GEN-LAST:event_btn_SearchClientDeleteActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        if(!(txt_IDdelete.getText().equals(""))){
        Client client=Counter.getInstance().getClientByLocker(Integer.valueOf(txt_IDdelete.getText()));
                if (client!=null){
                    Counter.getInstance().delete_client(client.get_ID());
                    JOptionPane.showMessageDialog(null,"El cliente ha sido eliminado");
                    cbox_TypeDelete.setSelectedIndex(0);
                    txt_IDdelete.setText("");  
                    lbl_NameDelete.setText("");
                    lbl_NameResultDelete.setText("");
                }
        }else{
            JOptionPane.showMessageDialog(null,"No puede eliminar sin haber completado la informacion solicitada");
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_SearchClientINFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchClientINFOActionPerformed
        // TODO add your handling code here:
        
        if(cbox_TypeINFO.getSelectedItem().toString().equals(" ")){
             JOptionPane.showMessageDialog(null,"Debe seleccionar un tipo de busqueda");
        }else{
        if(cbox_TypeINFO.getSelectedItem().toString().equals("Identificación del cliente")){
            if(!(txt_ID_INFO.getText().equals(""))){
                Client client=Counter.getInstance().getClient(Integer.valueOf(txt_ID_INFO.getText()));
                if (client!=null){
                    lbl_nameINFO.setText(client.get_name());
                    lbl_ID_INFO.setText(String.valueOf(client.get_ID()));
                    lbl_emailINFO.setText(client.get_email());
                    lbl_phoneINFO.setText(String.valueOf(client.get_phone()));
                    lbl_DirectionINFO.setText(client.get_direction());
                    lbl_birthdayINFO.setText(client.get_birthday());
                    lbl_genderINFO.setText(client.get_gender());
            }
            else{
                JOptionPane.showMessageDialog(null,"La identificacion ingresada no pertenece a nincuno de nuestros clientes,"
                                                + "inténtelo de nuevo");
            }
        }else{
                JOptionPane.showMessageDialog(null,"Debe ingersar un numero de identificacion");
            }
     }else{
            if(!(txt_ID_INFO.getText().equals(""))){
                Client client=Counter.getInstance().getClientByLocker(Integer.valueOf(txt_ID_INFO.getText()));
                if (client!=null){
                    
                    lbl_nameINFO.setText(client.get_name());
                    lbl_ID_INFO.setText(String.valueOf(client.get_ID()));
                    lbl_emailINFO.setText(client.get_email());
                    lbl_phoneINFO.setText(String.valueOf(client.get_phone()));
                    lbl_DirectionINFO.setText(client.get_direction());
                    lbl_birthdayINFO.setText(client.get_birthday());
                    lbl_genderINFO.setText(client.get_gender());
                }
                else{
                    JOptionPane.showMessageDialog(null,"El número de casillero ingresado no pertenece a ninguno de nuestros clientes, "
                                                    + "inténtelo de nuevo");
                }
            }else{
                    JOptionPane.showMessageDialog(null,"Debe ingersar un numero de casillero");
                }
            
            }   
            
        }
        
                                                          

        
        
    }//GEN-LAST:event_btn_SearchClientINFOActionPerformed

    private void btn_returnBackConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnBackConsultActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_returnBackConsultActionPerformed

    private void btn_ReturnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReturnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_ReturnBackActionPerformed

    private void btn_ReturnBackModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReturnBackModifyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_ReturnBackModifyActionPerformed

    private void btn_ReturnBackfromDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReturnBackfromDeleteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_ReturnBackfromDeleteActionPerformed

    private void btn_returnBackfromInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnBackfromInfoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_returnBackfromInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
            Counter Aerostore=new Counter("Aerostore",1234, "heredia",1);
//            
//            Aerostore.add_client(304900952,"Liryel", "bmiranda@.com", 12345678, "paraiso cartago", "H","18/11/1995");
//            
//            Magazine deliver= new Magazine(true, "revista de cocina mediterranea", "yor",3123, "cocina mediterranea", false, "cocina");
//            Aerostore.saveDeliveryMagazine(304900952, deliver);
//            Package deliver1=new Package(true,"computadora mac","yorley",100,true,true,40);
//            Aerostore.saveDeliveryPackage(304900952, deliver1);
//            Package deliver2=new Package(true,"almohadas","yorley",14513,true,true,60);
//            Aerostore.saveDeliveryPackage(304900952, deliver2);
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Register_Panel;
    private javax.swing.JPanel Register_Panel1;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_ModifyClient;
    private javax.swing.JButton btn_ReturnBack;
    private javax.swing.JButton btn_ReturnBackModify;
    private javax.swing.JButton btn_ReturnBackfromDelete;
    private javax.swing.JButton btn_SearchClientConsult;
    private javax.swing.JButton btn_SearchClientDelete;
    private javax.swing.JButton btn_SearchClientINFO;
    private javax.swing.JButton btn_SearchClientModify;
    private javax.swing.JButton btn_addClient;
    private javax.swing.JButton btn_returnBackConsult;
    private javax.swing.JButton btn_returnBackfromInfo;
    private javax.swing.JComboBox cbox_GenderRegister;
    private javax.swing.JComboBox cbox_TypeConsult;
    private javax.swing.JComboBox cbox_TypeDelete;
    private javax.swing.JComboBox cbox_TypeINFO;
    private javax.swing.JComboBox cbox_typeModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_Bierthday;
    private javax.swing.JLabel lbl_Bierthday1;
    private javax.swing.JLabel lbl_CodeDelieveryConsult;
    private javax.swing.JLabel lbl_CodeDelieveryConsult1;
    private javax.swing.JLabel lbl_CodeDelieveryConsult2;
    private javax.swing.JLabel lbl_DescriptionDeliveryConsult;
    private javax.swing.JLabel lbl_DescriptionDeliveryConsult1;
    private javax.swing.JLabel lbl_DescriptionDeliveryConsult2;
    private javax.swing.JLabel lbl_Direction;
    private javax.swing.JLabel lbl_Direction1;
    private javax.swing.JLabel lbl_DirectionINFO;
    private javax.swing.JLabel lbl_DirectionModify;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Email1;
    private javax.swing.JLabel lbl_EmailModify;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_Gender1;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_ID1;
    private javax.swing.JLabel lbl_ID_INFO;
    private javax.swing.JLabel lbl_InstructionCompleteData;
    private javax.swing.JLabel lbl_InstructionCompleteData1;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Name1;
    private javax.swing.JLabel lbl_NameDelete;
    private javax.swing.JLabel lbl_NameResultDelete;
    private javax.swing.JLabel lbl_PhoneNumber;
    private javax.swing.JLabel lbl_PhoneNumber1;
    private javax.swing.JLabel lbl_PhoneNumberModify;
    private javax.swing.JLabel lbl_RemittentConsult;
    private javax.swing.JLabel lbl_RemittentConsult1;
    private javax.swing.JLabel lbl_RemittentConsult2;
    private javax.swing.JLabel lbl_TypeConsultConsult;
    private javax.swing.JLabel lbl_TypeConsultConsult1;
    private javax.swing.JLabel lbl_TypeConsultDelete;
    private javax.swing.JLabel lbl_TypeDeliveryConsult;
    private javax.swing.JLabel lbl_TypeDeliveryConsult1;
    private javax.swing.JLabel lbl_TypeDeliveryConsult2;
    private javax.swing.JLabel lbl_TypeDeliveryConsult3;
    private javax.swing.JLabel lbl_birthdayINFO;
    private javax.swing.JLabel lbl_dateDelivery;
    private javax.swing.JLabel lbl_dateDelivery1;
    private javax.swing.JLabel lbl_dateDelivery2;
    private javax.swing.JLabel lbl_emailINFO;
    private javax.swing.JLabel lbl_genderINFO;
    private javax.swing.JLabel lbl_nameINFO;
    private javax.swing.JLabel lbl_phoneINFO;
    private javax.swing.JLabel lbl_statusDeliveryConsult;
    private javax.swing.JLabel lbl_statusDeliveryConsult1;
    private javax.swing.JLabel lbl_statusDeliveryConsult2;
    private javax.swing.JLabel lbl_typeModify;
    private javax.swing.JPanel panel_Consult;
    private javax.swing.JPanel panel_Delete;
    private javax.swing.JPanel panel_EnvelopeConsult;
    private javax.swing.JPanel panel_MagazineConsult;
    private javax.swing.JPanel panel_PackageConsult;
    private javax.swing.JTabbedPane tbdpanel_Client;
    private javax.swing.JTextField txt_Birthday;
    private javax.swing.JTextField txt_Direction;
    private javax.swing.JTextField txt_DirectionModify;
    private javax.swing.JTextField txt_EmailModify;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_IDConsult;
    private javax.swing.JTextField txt_IDModify;
    private javax.swing.JTextField txt_ID_INFO;
    private javax.swing.JTextField txt_IDdelete;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_PhoneNumberModify;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_phoneNumber;
    // End of variables declaration//GEN-END:variables
}
