/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author YorleydeMaría
 */
public class Costs_View extends javax.swing.JFrame {

    /**
     * Creates new form Costs_View
     */
    public Costs_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Costs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_CostsDisplay = new javax.swing.JPanel();
        lbl_Code = new javax.swing.JLabel();
        lbl_Type = new javax.swing.JLabel();
        lbl_Tax = new javax.swing.JLabel();
        lbl_Disscount = new javax.swing.JLabel();
        lbl_Colones = new javax.swing.JLabel();
        lbl_Dollars = new javax.swing.JLabel();
        lbl_Bill = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_BuyText = new javax.swing.JLabel();
        lbl_SellText = new javax.swing.JLabel();
        lbl_Buy = new javax.swing.JLabel();
        lbl_Sell = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_CostsDisplay.setPreferredSize(new java.awt.Dimension(634, 1000));

        javax.swing.GroupLayout panel_CostsDisplayLayout = new javax.swing.GroupLayout(panel_CostsDisplay);
        panel_CostsDisplay.setLayout(panel_CostsDisplayLayout);
        panel_CostsDisplayLayout.setHorizontalGroup(
            panel_CostsDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        panel_CostsDisplayLayout.setVerticalGroup(
            panel_CostsDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_CostsDisplay);

        lbl_Code.setText("Código");

        lbl_Type.setText("Tipo");

        lbl_Tax.setText("Impuesto");

        lbl_Disscount.setText("Descuento");

        lbl_Colones.setText("Total Colones");

        lbl_Dollars.setText("Total Dolares");

        lbl_Bill.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbl_Bill.setText("Facturacion");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tipo de Cambio ");

        lbl_BuyText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_BuyText.setText("Compra");

        lbl_SellText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_SellText.setText("Venta");

        lbl_Buy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_Buy.setText("00000.0");

        lbl_Sell.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_Sell.setText("00000.0");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Cobrar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tipo de pago");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contado", "American Express", "Visa", "Master Card" }));

        jLabel3.setText("Monto Total:");

        jLabel4.setText("000000.0");

        jLabel5.setText("$");

        jLabel6.setText("000000.0");

        jLabel7.setText("₡");

        javax.swing.GroupLayout panel_CostsLayout = new javax.swing.GroupLayout(panel_Costs);
        panel_Costs.setLayout(panel_CostsLayout);
        panel_CostsLayout.setHorizontalGroup(
            panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CostsLayout.createSequentialGroup()
                .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_CostsLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Bill)
                            .addGroup(panel_CostsLayout.createSequentialGroup()
                                .addGap(376, 376, 376)
                                .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_BuyText)
                                    .addComponent(lbl_Buy)))))
                    .addGroup(panel_CostsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_CostsLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_CostsLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(lbl_Code)
                                    .addGap(56, 56, 56)
                                    .addComponent(lbl_Type)
                                    .addGap(69, 69, 69)
                                    .addComponent(lbl_Tax)
                                    .addGap(47, 47, 47)
                                    .addComponent(lbl_Disscount)
                                    .addGap(55, 55, 55)
                                    .addComponent(lbl_Colones)
                                    .addGap(51, 51, 51)
                                    .addComponent(lbl_Dollars))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(panel_CostsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_CostsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_CostsLayout.createSequentialGroup()
                                .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_SellText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_Sell, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(33, 33, 33))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panel_CostsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_CostsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(108, 108, 108))
        );
        panel_CostsLayout.setVerticalGroup(
            panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_CostsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_Bill)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_CostsLayout.createSequentialGroup()
                        .addComponent(lbl_SellText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Sell))
                    .addGroup(panel_CostsLayout.createSequentialGroup()
                        .addComponent(lbl_BuyText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Buy)))
                .addGap(18, 18, 18)
                .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Code)
                    .addComponent(lbl_Type)
                    .addComponent(lbl_Tax)
                    .addComponent(lbl_Disscount)
                    .addComponent(lbl_Colones)
                    .addComponent(lbl_Dollars))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addGroup(panel_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_Costs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_Costs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Costs_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Costs_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Costs_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Costs_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Costs_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Bill;
    private javax.swing.JLabel lbl_Buy;
    private javax.swing.JLabel lbl_BuyText;
    private javax.swing.JLabel lbl_Code;
    private javax.swing.JLabel lbl_Colones;
    private javax.swing.JLabel lbl_Disscount;
    private javax.swing.JLabel lbl_Dollars;
    private javax.swing.JLabel lbl_Sell;
    private javax.swing.JLabel lbl_SellText;
    private javax.swing.JLabel lbl_Tax;
    private javax.swing.JLabel lbl_Type;
    private javax.swing.JPanel panel_Costs;
    private javax.swing.JPanel panel_CostsDisplay;
    // End of variables declaration//GEN-END:variables
}
